# RustSlicer Default PLA Profile

[metadata]
profile_name = "Default PLA Profile"
version = "1.0"
author = "Philipp"

[machine]
printer_type = "cartesian"
build_volume = [220.0, 220.0, 250.0]  # X, Y, Z in mm
nozzle_diameter = 0.4
filament_diameter = 1.75
max_feedrate = [300.0, 300.0, 12.0, 80.0]  # X, Y, Z, E in mm/s
max_acceleration = [3000.0, 3000.0, 100.0, 5000.0]

[print_settings]
layer_height = 0.2
first_layer_height = 0.3
line_width = 0.4
perimeters = 3
external_perimeter_speed = 40.0
perimeter_speed = 60.0
top_solid_layers = 4
bottom_solid_layers = 3
infill_density = 0.20  # 20%
infill_pattern = "gyroid"
infill_speed = 80.0
solid_infill_speed = 60.0
support_material = false

[material]
material_type = "PLA"
nozzle_temperature = 210
bed_temperature = 60
first_layer_nozzle_temp = 215
first_layer_bed_temp = 65
fan_speed = 100  # 0-100%

[advanced]
retraction_length = 5.0
retraction_speed = 40.0
retraction_z_lift = 0.2

[gcode]
gcode_flavor = "marlin"
use_relative_e = false

start_gcode = """
G28 ; Home all axes
G1 Z15.0 F6000 ; Move platform down
G92 E0 ; Reset extruder
G1 F200 E3 ; Extrude a short distance
G92 E0 ; Reset extruder again
"""

end_gcode = """
M104 S0 ; Turn off hotend
M140 S0 ; Turn off bed
G91 ; Relative positioning
G1 E-2 F2700 ; Retract
G1 Z10 ; Raise Z
G90 ; Absolute positioning
G28 X Y ; Home X Y
M84 ; Disable motors
"""
